IRREGULAR_VERBS = {
    "abc": {
        "description": "Все три формы разные (A-B-C)",
        "verbs": [
            ("be", "was/were", "been", "быть"),
            ("begin", "began", "begun", "начинать"),
            ("bite", "bit", "bitten", "кусать"),
            ("blow", "blew", "blown", "дуть"),
            ("break", "broke", "broken", "ломать"),
            ("choose", "chose", "chosen", "выбирать"),
            ("do", "did", "done", "делать"),
            ("draw", "drew", "drawn", "рисовать"),
            ("drink", "drank", "drunk", "пить"),
            ("drive", "drove", "driven", "водить"),
            ("eat", "ate", "eaten", "есть"),
            ("fall", "fell", "fallen", "падать"),
            ("fly", "flew", "flown", "летать"),
            ("forget", "forgot", "forgotten", "забывать"),
            ("give", "gave", "given", "давать"),
            ("go", "went", "gone", "идти"),
            ("grow", "grew", "grown", "расти"),
            ("hide", "hid", "hidden", "прятать"),
            ("know", "knew", "known", "знать"),
            ("lie", "lay", "lain", "лежать"),
            ("ride", "rode", "ridden", "ехать верхом"),
            ("ring", "rang", "rung", "звонить"),
            ("rise", "rose", "risen", "подниматься"),
            ("see", "saw", "seen", "видеть"),
            ("show", "showed", "shown", "показывать"),
            ("sing", "sang", "sung", "петь"),
            ("speak", "spoke", "spoken", "говорить"),
            ("steal", "stole", "stolen", "красть"),
            ("swim", "swam", "swum", "плавать"),
            ("take", "took", "taken", "брать"),
            ("throw", "threw", "thrown", "бросать"),
            ("wake", "woke", "woken", "просыпаться"),
            ("wear", "wore", "worn", "носить (одежду)"),
            ("write", "wrote", "written", "писать"),
        ],
    },
    "abb": {
        "description": "Вторая и третья формы совпадают (A-B-B)",
        "verbs": [
            ("bring", "brought", "brought", "приносить"),
            ("build", "built", "built", "строить"),
            ("burn", "burnt", "burnt", "жечь"),
            ("buy", "bought", "bought", "покупать"),
            ("catch", "caught", "caught", "ловить"),
            ("feed", "fed", "fed", "кормить"),
            ("feel", "felt", "felt", "чувствовать"),
            ("fight", "fought", "fought", "бороться"),
            ("find", "found", "found", "находить"),
            ("get", "got", "got", "получать"),
            ("have", "had", "had", "иметь"),
            ("hear", "heard", "heard", "слышать"),
            ("hold", "held", "held", "держать"),
            ("keep", "kept", "kept", "хранить"),
            ("lead", "led", "led", "вести"),
            ("learn", "learnt", "learnt", "учиться"),
            ("leave", "left", "left", "уходить"),
            ("lend", "lent", "lent", "одалживать"),
            ("lose", "lost", "lost", "терять"),
            ("make", "made", "made", "делать"),
            ("mean", "meant", "meant", "значить"),
            ("meet", "met", "met", "встречать"),
            ("pay", "paid", "paid", "платить"),
            ("read", "read", "read", "читать"),
            ("say", "said", "said", "говорить"),
            ("sell", "sold", "sold", "продавать"),
            ("send", "sent", "sent", "отправлять"),
            ("sit", "sat", "sat", "сидеть"),
            ("sleep", "slept", "slept", "спать"),
            ("spend", "spent", "spent", "тратить"),
            ("stand", "stood", "stood", "стоять"),
            ("teach", "taught", "taught", "учить"),
            ("tell", "told", "told", "рассказывать"),
            ("think", "thought", "thought", "думать"),
            ("understand", "understood", "understood", "понимать"),
            ("win", "won", "won", "выигрывать"),
        ],
    },
    "aba": {
        "description": "Первая и третья формы совпадают (A-B-A)",
        "verbs": [
            ("become", "became", "become", "становиться"),
            ("come", "came", "come", "приходить"),
            ("overcome", "overcame", "overcome", "преодолевать"),
            ("run", "ran", "run", "бежать"),
        ],
    },
    "aaa": {
        "description": "Все три формы одинаковые (A-A-A)",
        "verbs": [
            ("bet", "bet", "bet", "делать ставку"),
            ("cost", "cost", "cost", "стоить"),
            ("cut", "cut", "cut", "резать"),
            ("hit", "hit", "hit", "ударять"),
            ("hurt", "hurt", "hurt", "причинять боль"),
            ("let", "let", "let", "позволять"),
            ("put", "put", "put", "класть"),
            ("quit", "quit", "quit", "бросать"),
            ("set", "set", "set", "устанавливать"),
            ("shut", "shut", "shut", "закрывать"),
            ("spread", "spread", "spread", "распространять"),
        ],
    },
}
